services:
  customer:
    container_name: woojin_customer
    env_file: .env
    environment:
      - NODE_ENV=development
    build:
      dockerfile: ./Dockerfile
      target: customer
    image: customer
    pull_policy: build
    restart: unless-stopped
    ports:
      - "81:3000"
    command: yarn dev

  order:
    container_name: woojin_order
    env_file: .env
    environment:
      - NODE_ENV=development
    build:
      dockerfile: ./Dockerfile
      target: order
    image: order
    pull_policy: build
    restart: unless-stopped
    ports:
      - "82:3000"
    command: yarn dev

  database:
    container_name: woojin_postgres
    environment:
      - POSTGRES_PASSWORD=660900
    image: postgres:16
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    expose:
      - "5432"

volumes:
  pgdata: